### ISSUE TITLE
Allow platform URL to be selected on first app startup

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusandroid#23]
If we want to get a standard arcusandroid app into the play store, then it would be useful if the user can select the platform to login to without having to build the app and ad-hoc distribute it, or need to login to a platform to get the debug menu up to switch places.

Can we make the login screen prompt the user to enter the platform URL on first-start if it was left at "https://arcus.example.com" or such during the build/distribution cycle?

**Comment by eanderso** [comment]
The way it's setup right now that may be tricky to have an input box below password or something.. However, you can always use the debug Menu from the login screen - three pinch out (zoom in style pinch) - and set the URL there. That will cause a restart of the app since the URLs are static currently.
